name: churn
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5=2_gnu
  - asttokens=3.0.0=pyhd8ed1ab_1
  - brotli=1.2.0=h2d644bc_1
  - brotli-bin=1.2.0=hfd05255_1
  - bzip2=1.0.8=h0ad9c76_8
  - ca-certificates=2025.11.12=h4c7d964_0
  - cairo=1.18.4=h5782bbf_0
  - certifi=2025.8.3=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.0=py39h2b77a98_2
  - cpython=3.9.23=py39hd8ed1ab_0
  - cudatoolkit=11.2.2=h7d7167e_13
  - cudnn=8.1.0.77=h3e0f4f4_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - debugpy=1.8.16=py39h1f3cc84_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - double-conversion=3.3.1=he0c23c2_0
  - et_xmlfile=2.0.0=pyhd8ed1ab_1
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h765892d_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.59.1=py39h5769e4c_0
  - freetype=2.14.1=h57928b3_0
  - graphite2=1.3.14=hac47afa_2
  - harfbuzz=11.0.0=h9e37d49_0
  - icu=75.1=he0c23c2_0
  - imbalanced-learn=0.12.4=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - importlib-resources=6.5.2=pyhd8ed1ab_0
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - ipykernel=6.30.1=pyh3521513_0
  - ipython=8.18.1=pyh7428d3b_3
  - jedi=0.19.2=pyhd8ed1ab_1
  - joblib=1.5.1=pyhd8ed1ab_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh5737063_0
  - kiwisolver=1.4.7=py39h2b77a98_0
  - krb5=1.21.3=hdf4eb48_0
  - lcms2=2.17=hbcf6048_0
  - lerc=4.0.0=h6470a55_1
  - libblas=3.11.0=2_hf2e6a31_mkl
  - libbrotlicommon=1.2.0=hfd05255_1
  - libbrotlidec=1.2.0=hfd05255_1
  - libbrotlienc=1.2.0=hfd05255_1
  - libcblas=3.11.0=2_h2a3cdd5_mkl
  - libclang13=21.1.6=default_ha2db4b5_0
  - libdeflate=1.25=h51727cc_0
  - libexpat=2.7.3=hac47afa_0
  - libffi=3.5.2=h52bdfb6_0
  - libfreetype=2.14.1=h57928b3_0
  - libfreetype6=2.14.1=hdbac1cb_0
  - libgcc=15.2.0=h8ee18e1_12
  - libglib=2.84.0=h7025463_0
  - libgomp=15.2.0=h8ee18e1_12
  - libhwloc=2.12.1=default_h88281d1_1000
  - libiconv=1.18=hc1393d2_2
  - libintl=0.22.5=h5728263_3
  - libjpeg-turbo=3.1.2=hfd05255_0
  - liblapack=3.11.0=2_hf9ab0e9_mkl
  - liblzma=5.8.1=h2466b09_2
  - libpng=1.6.51=h7351971_0
  - libsodium=1.0.20=hc70643c_0
  - libsqlite=3.51.0=hf5d6505_0
  - libtiff=4.7.1=h8f73337_1
  - libwebp-base=1.6.0=h4d5522a_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_10
  - libxcb=1.17.0=h0e4246c_0
  - libxml2=2.13.9=h741aa76_0
  - libxslt=1.1.43=h25c3957_0
  - libzlib=1.3.1=h2466b09_2
  - llvm-openmp=21.1.6=h4fa8253_0
  - matplotlib=3.9.4=py39hcbf5309_0
  - matplotlib-base=3.9.4=py39h5376392_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mkl=2025.3.0=hac47afa_454
  - munkres=1.1.4=pyhd8ed1ab_1
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - numpy=1.26.4=py39hddb5d58_0
  - openjpeg=2.5.4=h24db6dd_0
  - openpyxl=3.1.5=py39ha55989b_1
  - openssl=3.6.0=h725018a_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.1=py39h743b7ac_0
  - parso=0.8.4=pyhd8ed1ab_1
  - patsy=1.0.1=pyhd8ed1ab_1
  - pcre2=10.44=h99c9b8b_2
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.3.0=py39hbad85af_0
  - pip=25.2=pyh8b19718_0
  - pixman=0.46.4=h5112557_1
  - platformdirs=4.3.8=pyhe01879c_0
  - prompt-toolkit=3.0.51=pyha770c72_0
  - psutil=7.0.0=py39ha55e580_0
  - pthread-stubs=0.4=h0e40799_1002
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyparsing=3.2.3=pyhe01879c_2
  - pyside6=6.9.0=py39h5cc861e_0
  - python=3.9.23=h8c5b53a_0_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.9=8_cp39
  - pytz=2025.2=pyhd8ed1ab_0
  - pywin32=311=py39h5fb4b08_0
  - pyzmq=27.0.2=py39h248659b_0
  - qhull=2020.2=hc790b64_5
  - qt6-main=6.9.0=h83cda92_0
  - scikit-learn=1.3.2=py39h7c199eb_2
  - scipy=1.13.1=py39h1a10956_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - statsmodels=0.14.5=py39h9e4d2f2_0
  - tbb=2022.3.0=hd094cb3_1
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.13=h2c6b04d_3
  - tornado=6.5.2=py39h0802e32_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.14.1=pyhe01879c_0
  - tzdata=2025b=h78e105d_0
  - ucrt=10.0.26100.0=h57928b3_0
  - unicodedata2=16.0.0=py39ha55e580_0
  - vc=14.3=h2b53caa_32
  - vc14_runtime=14.44.35208=h818238b_32
  - vcomp14=14.44.35208=h818238b_32
  - vs2015_runtime=14.44.35208=h38c0c73_32
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - xorg-libxau=1.0.12=hba3369d_1
  - xorg-libxdmcp=1.1.5=hba3369d_1
  - zeromq=4.3.5=h5bddc39_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zstd=1.5.7=hbeecb71_2
  - pip:
      - absl-py==2.3.1
      - astunparse==1.6.3
      - cachetools==6.2.2
      - charset-normalizer==3.4.4
      - flatbuffers==25.9.23
      - gast==0.4.0
      - google-auth==2.43.0
      - google-auth-oauthlib==0.4.6
      - google-pasta==0.2.0
      - grpcio==1.76.0
      - h5py==3.14.0
      - idna==3.11
      - keras==2.10.0
      - keras-preprocessing==1.1.2
      - libclang==18.1.1
      - markdown==3.9
      - markupsafe==3.0.3
      - oauthlib==3.3.1
      - opt-einsum==3.4.0
      - protobuf==3.19.6
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - requests==2.32.5
      - requests-oauthlib==2.0.0
      - rsa==4.9.1
      - scikeras==0.11.0
      - tensorboard==2.10.1
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorflow==2.10.1
      - tensorflow-estimator==2.10.0
      - tensorflow-io-gcs-filesystem==0.31.0
      - termcolor==3.1.0
      - urllib3==2.5.0
      - werkzeug==3.1.3
      - wrapt==2.0.1
prefix: C:\ProgramData\anaconda3\envs\churn
